version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
      enabled: true
      reject_regex: ^Rejected
    required: 2
    reset_on_push:
      enabled: true
    users:
    - jiyeonseo