language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true
env:
  global:
    - secure: "QqA6zwxXE9RgMr8AbZL7sHvU8zp9TVSZbgwSikCkiybcahDTz97+HM1tSOsn1tW0cxrW8RI6n/DFSOH7Y+OkEn6p5sCE+0pU83SeLniQ1pOQ8EAenwVxnHEZlYLTEwPwHRodozY1kQPZL56oU8D0z5HD7LrP4uJg3BB/VuVfxNF+bBuG+RcjcslIb7Kgi6D5LvmNHBBjFzUGFqVbKH5QFeiywZprV4JyrhzgnnDaFbSFvjMKtJIeyJNhJA0uEbbMzRFb9X4QIUCtZSTtQsK3T4/StsXdXesy8IRqJ7FEI68oESxY+9OqdYb1Hg8zIb9q5KMIQ0tNm0CsYYSlO8E7E2KM3i+0+znJSXKq3guADYOTHJezxXgMqA+RV2hgBwfrIgLZOLt/9IAKbnLtMA2320YQSfhqRqUH9wXMGsBV5/ObAzPMddhPr3S8lfMJHLWa5vJm/11Hy+MKG4DhMzre7xyhdkJS2s5zpKhWhZnDvhvYLdFdX8FhNIT4qH2Dga211obAOXLsTGQ4h9G1tlNFYEu9EQFw1bOpq12oOCicofiQp4FXv/2zdheTnQ8U3zll6QxJ4bBlSqnzdoVKTd7I4sOkQ88Ga469ade6YH4pOkKMwmJHu4CcBcKihppIzARDNgOvlqDfMarj6bY5B53nPRn2d719CcxzSqrCd0yFxd8="
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN